name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "5,10,15,20,25,30,35,40,45,50,55 * * * *"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get -y install libmysqlclient-dev
      - uses: open-turo/actions-python/lint@v1
